# import json,os
# import sys
# sys.path.append('/nlp_group/chenzhengzong/rm_dataset/gpt4_api')
# from kess.framework import (
#     ClientOption,
#     GrpcClient,
#     KessOption
# )

# from google.protobuf.json_format import MessageToJson
# # 此处xxx，填写使用者具体项目中编译pb文件后的具体地址，
# # 可以自行编译上述pb文件，也可以直接使用上述编译后的pb文件
# from mmu.mmu_chat_gpt_pb2_grpc import (
#     MmuChatGptServiceStub,
# )

# from mmu.mmu_chat_gpt_pb2 import MmuChatGptRequest, MmuChatGptResponse

# os.environ['KWS_SERVICE_AZ']='HB2AZ1'
# os.environ['KWS_SERVICE_REGION']='HB2'
# os.environ['KWS_SERVICE_DC']='WLF2'
# os.environ['KWS_SERVICE_NAME']='ai-platform-dense-server'
# os.environ['KWS_SERVICE_CATALOG']='ai-platform.ksnserver.dense-server'
# os.environ['KWS_SERVICE_STAGE']='PROD'

# client_option = ClientOption(
# 	biz_def='mmu', # 公司侧rpcmonitor业务唯一标识，比如mmu、web_server等
#   grpc_service_name= 'mmu-chat-gpt-service',
#   grpc_stub_class=MmuChatGptServiceStub
# )

# grpc_client = GrpcClient(client_option)
# prompt="有一段用户与客服的对话，会话内容如下：\n{quest}\n请帮忙提取如下信息\n1、用户是否有装修意愿：请回答用户是否有装修意愿，1表示有，2表示没有。\n2、用户的房屋地址-省：请提供用户房屋所在省份。\n3、用户的房屋地址-市：请提供用户房屋所在城市。\n4、用户的房屋地址-区：请提供用户房屋所在区县。\n5、用户的房屋地址-具体地址：请提供用户房屋的具体地址。\n6、用户的房屋面积：请提供用户房屋的建筑面积。\n7、用户的户型-卧室数量：请提供用户房屋的卧室数量。\n8、用户的户型-客厅数量：请提供用户房屋的客厅数量。\n9、用户的户型-卫生间数量：请提供用户房屋的卫生间数量。\n10、用户的预期量房时间-精确到日期：请提供用户预期量房的日期。\n11、用户的预期装修时间-精确到日：请提供用户预期装修的时间，精确到日。\n12、用户的房屋新旧：请提供用户房屋的新旧程度，1表示毛坯，2表示翻新。\n13、用户装修的项目类型：请提供用户装修的项目类型，1表示家装，2表示公装。\n14、用户装修的房屋用途：请提供用户装修的房屋用途，1表示自用，2表示出租。\n15、用户房屋装修的工程量：请提供用户装修的工程量，1表示整体，2表示局部，3表示单项施工，4表示定制。\n16、用户的房屋类别：请提供用户房屋的类别，1表示住宅公寓，2表示别墅，3表示阁楼，4表示自建房，5表示复式，6表示其他。\n17、用户的房屋是否已交房：请提供用户房屋是否已交房，1表示已交房，2表示未交房。\n18、用户的装修总预算-精确到万：请提供用户装修的总预算，精确到万 ，若未提及，请说无"

# #val="客户：嗯。\n客服：你好，哎，这里是快手家庄的，您这边有房子要装修，在做前期的对比是吗？\n客户：你数算。\n客服：我这边是快手家装业务。\n客服：官方平台就是看到您在快手上有提交过一条装修的一项咨询，就是问一下看您是不是有房标装修。\n客户：对，有房子装修。\n客服：嗯，您这个是新房装修吗？还是老房分新。\n客户：新房对。\n客服：新房是毛坯房吗？嗯？\n客服：是这样，咱们这边呢是官方平台，就是每个地方，呃，全国各地都是有门店的。\n客服：咱们可以帮您安排几家，就是推荐几家这个装修公司，您可以做一个免费的量房。\n客服：还有一个装修方案，嗯，看您什么时间方便呢，您这个下房了吗？\n客户：你说啥免费来疗房。\n客服：就是可以帮您推荐几家装修公司，给您做一个免费的量房，出个装修方案。\n客户：在在哪，哎，大同，我是大同的。\n客服：嗯，您这个是。\n客服：我们在全，我们在全国各地都是有门店的啊，我们是官方平台。\n客户：哦，那多会儿多会儿了，去看看免费看了是吧？\n客服：对，粮房这个都是免费的，不收费。\n客户：哦，那行，多会儿。\n客服：嗯，您家这个现在已经下房了是吧，现在已经下房了。\n客户：你说啥哦。\n客服：嗯，行，您什么时间方便，就是我们现在预约的话可能要到明天或者是之后。\n客服：就明天以后你哪天方便的话，嗯你，嗯。\n客户：最好是明天明天。\n客服：明天可以是吧，明天什么时间呀？\n客户：哦，明天下午。\n客服：下午好的下午几点，下午几点。\n客户：哦，你姓啥？\n客户：下午下午三点左右哇。\n客服：三点左右可以是吧，行行，您这个，您这个具体具理位置在哪，我帮您记一下。\n客户：哦。\n客户：哦，你记一下这。\n客户：这个在那哪就白马城，大同白马城。\n客服：嗯，是山西省太原市吗？\n客户：我是大同。\n客服：呃，山西省大同市是吧，大同市，然后是什么区。\n客户：昂，有你们的施工的人没？\n客户：是平城区。\n客户：对。\n客服：平城区，嗯，小区名字是什么？\n客户：后区名字是梦晓，家园梦晓。\n客服：孟梦城家园吗，孟晓。\n客户：梦想家园，对。\n客服：梦晓家园是吧，嗯，稍等我查一下。\n客户：费人入点费支26号自人号不。\n客服：梦是梦，是孟子那个梦吗？姓孟的梦。\n客户：叫中梦的么，嗯。\n客服：做梦的梦脚是哪个脚呀？\n客户：梦想心小的小，小东西的小对。\n客服：梦想是吗，天瑞梦想家园是吗？\n客户：哦。\n客服：哎，好的，那我已经收到了，然后您家这个是打算什么时间装啊，什么时间动工。\n客户：哦，我这就想动弹了么，他来给我看看这个。\n客户：嗯，他那个量一下房，看看他咋设计的图咋的，看这价位咋的。\n客服：嗯，主要是要看一下，就是咱们这个报价呀，还有一些。\n客服：是不是符合您的要求，那如果就合适的话，您打算是大概什么时间动工？\n客户：他看完我才能定了，呵，那肯定是这阵儿就想做了么那。\n客服：就是这个意思就是啊，就看你要预期动工时间，是说是最近呢还是说是。\n客户：北京最近，嗯。\n客服：在过最近呢啊，行，那明白了，哎，然后您这个房屋面积是多大的。\n客户：100多。\n客服：100大概多少知道吗？嗯，100多平。\n客户：最多个0708，哇这这。\n客户：不不不，你是你是咱完我他是去给我看看是个啥设计好是不到点儿凉房是不这样儿的。\n客户：啥意思？\n客服：嗯嗯，就是帮您先登记一下。\n客服：根据您的这个房屋面积地理位置，帮您推荐几个靠谱的公司，然后您对比一下。\n客户：嗯，推荐完干啥？\n客服：您这个是几时几厅几位？\n客户：哦，你，你跟我说他这个流程他去是啥意思？\n客服：他去是帮你做一个免费的粮房，就是。\n客服：根据您家的房型具体面积帮您推荐，就是帮您做一个规划啊，装修方案。\n客户：来不来。\n客服：如果您觉得合适您再用，如果您觉得不合适，就当做个价钱对比，然后您再换一下，这都没问题。\n客户：哦，能行就能行，咱就装昂。\n客服：对，这个是不，嗯，这是不收费的。\n客户：哦，行，那你就明天给联系哇，能过去看看昂。\n客服：嗯，您对帮您预约好之后他会联系您的。\n客户：哦，行，嗯，好。\n客服：嗯，您这个是几室几厅几位给您登记一下。\n客户：一位小三一为。\n客服：嗯，一卫一厅，呃，几厅。\n客户：1室哎，一厅3室噢。\n客服：3室一厅是吧，哎，好的，那就先帮您预约到明天的。\n客服：啊，我看一下明天的下午三点啊，地址是天瑞梦想家园。\n客户：下午，哎，对行。\n客户：嗯，对权利，嗯。\n客服：嗯，好的，那女士您贵姓林女士。\n客服：然后稍后呢，这个装修公司会在亲自联系您和您最中确认一下量房的时间。\n客服：您保持电话畅通，那就先不打扰您了啊，再见。\n客户：哦哦嗯，行了，谢谢。"

# data=[json.loads(x) for x in open('/nlp_group/chenzhengzong/rm_dataset/RM/home_decora/im_v1').readlines()]
# with open('/nlp_group/chenzhengzong/rm_dataset/RM/home_decora/im_v1_ans_kuaiyi','w') as f:
#   for d in data:
#       val=d['input']
#       request = MmuChatGptRequest(biz='api_test', session_id='1', req_id='11', query=prompt.format(quest=val))
#       resp = grpc_client.Chat(request, timeout=60)
#       resp=json.loads(MessageToJson(resp))
#       #print(resp)
#       d['answer']=resp['answer']
#       f.write(json.dumps(d,ensure_ascii=False)+'\n')

#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys,os
sys.path.append('/nlp_group/chenzhengzong/rm_dataset/gpt4_api')
import logging
import time
from google.protobuf.json_format import MessageToJson
import json
import random, time

from kess.framework import (
    ClientOption,
    GrpcClient,
    KessOption,
)

from mmu.mmu_chat_gpt_pb2 import MmuChatGptRequest,MmuChatGptResponse
from mmu.mmu_chat_gpt_pb2_grpc import (
     MmuChatGptServiceStub,
)
os.environ['KWS_SERVICE_AZ']='HB2AZ1'
os.environ['KWS_SERVICE_REGION']='HB2'
os.environ['KWS_SERVICE_DC']='WLF2'
os.environ['KWS_SERVICE_NAME']='ai-platform-dense-server'
os.environ['KWS_SERVICE_CATALOG']='ai-platform.ksnserver.dense-server'
os.environ['KWS_SERVICE_STAGE']='PROD'

logger = logging.getLogger(__name__)
fmt_str = ('%(asctime)s.%(msecs)03d %(levelname)7s '
           '[%(thread)d][%(process)d] %(message)s')
fmt = logging.Formatter(fmt_str, datefmt='%H:%M:%S')
handler = logging.StreamHandler()
handler.setFormatter(fmt)
logger.addHandler(handler)
logger.setLevel(logging.INFO)

prompt_format="我是「快意」，是一款由快手AI团队打造的大规模语言模型。我基于海量数据和知识持续迭代进化，拥有广泛的多领域知识和创作才能，具备出色的语言理解和生成能力，能够理解并高效执行各类任务。我擅长知识问答、文案创作、文字翻译、数学逻辑、代码理解和编写等任务，致力于全方位帮助用户解决各种问题，期待能够为你提供更智能、轻快的互动体验 。 问题: {question} 答案: "

def process_with_retry(grpc_client: GrpcClient, request, query, time_out, n_times, id_key):
    resp = None
    for i in range(n_times):
        try:
            #prompt='对于问题 "{quest}", 有如下多个答案, 请从正确性、完整性和表达清晰度等方面做0-10打分, 答案A: "{ansa}", 答案B: "{ansb}", 答案C: "{ansa}", 答案D: "{ansb}", 答案A得分:, 答案B得分:, 答案C得分:, 答案D得分:'
            #prompt='对于问题{{{quest}}}, 有如下多个答案, 请从正确性、完整性和表达清晰度等方面做0-10打分, 并给出最佳答案。\n答案A: {{{ansa}}} \n答案B: {{{ansb}}} \n答案A得分: \n答案B得分: \n最佳答案:'
            # prompt='对于问题: {quest} \n有如下多个答案, 请根据如下规则对答案做0-10打分, 并给出最佳答案，规则如下： \
            #     \n1.语言表达能力: 根据回答中的语法错误、拼写错误、重复词汇等自然语言处理技术分析得出的分数，以及情感分析得出的分数，综合评估回答的语言表达能力. \
            #     \n2.逻辑推理能力: 根据回答中的逻辑错误、循环论证、因果关系错误等问题，以及情感分析得出的分数，综合评估回答的逻辑推理能力。 \
            #     \n3.情感分析能力: 根据回答中的情感倾向，以及情感分析得出的分数，综合评估回答的情感分析能力。 \
            #     \n4.信息丰富度: 根据回答中的信息量、相关性、可信度等因素，以及自然语言处理技术得出的分数，综合评估回答的信息丰富度。 \
            #     \n5.可读性: 根据回答的可读性指标，如单词数量、句子长度、排版格式等，以及自然语言处理技术得出的分数，综合评估回答的可读性。 \
            #     \n答案A: {ansa} \n答案B: {ansb} \n答案A得分: \n答案B得分: \n最佳答案:'
            #两个答案打分
            #prompt="The question: {quest} \n has two answer, please evaluate the answers and give a score between 0 and 10, and choose the best answer. We can use the following principle: \
            #    \n1.Accuracy of the information: Assess the accuracy of the information provided by the assistant. This includes checking if the information is factual, up-to-date, and relevant to the question asked. \
            #    \n2.Clarity and coherence: Evaluate the clarity and coherence of the answer. Does it provide a clear and concise explanation of the topic? Is it well-organized and easy to follow? \
            #    \n3.Usefulness: Assess the usefulness of the information provided by the assistant. Does it provide practical solutions or insights that can help the user in their decision-making process? \
            #    \n4.Personalization: Evaluate the personalization of the answer. Does it take into account the user's needs, preferences, and goals? \
            #    \n5.Engagement: Assess the engagement level of the answer. Does it encourage the user to ask further questions or seek more information? \
            #    \nanswer A: {ansa} \nanswer B: {ansb} \nanswer A score: \nanswer B score: \nthe best answer:"
            #4个答案打分
            #prompt="The question: {quest} \n has four answer, please evaluate the answers and give a score between 0 and 10, and choose the best answer. We can use the following principle: \
            #    \n1.Accuracy of the information: Assess the accuracy of the information provided by the assistant. This includes checking if the information is factual, up-to-date, and relevant to the question asked. \
            #    \n2.Clarity and coherence: Evaluate the clarity and coherence of the answer. Does it provide a clear and concise explanation of the topic? Is it well-organized and easy to follow? \
            #    \n3.Usefulness: Assess the usefulness of the information provided by the assistant. Does it provide practical solutions or insights that can help the user in their decision-making process? \
            #    \n4.Personalization: Evaluate the personalization of the answer. Does it take into account the user's needs, preferences, and goals? \
            #    \n5.Engagement: Assess the engagement level of the answer. Does it encourage the user to ask further questions or seek more information? \
            #    \nanswer A: {ansa} \nanswer B: {ansb} \nanswer C: {ansc} \nanswer D: {ansd} \nanswer A score: \nanswer B score: \nanswer C score: \nanswer D score: \nthe best answer:"
            #针对性的判断
            #prompt="You are a helpful and precise assistant that selects the necessary skills required to respond to instructions.\nYou are given the following 12 skills.\n[Skill Options]\n1: 模型需要对自己能做什么、不能做什么,是什么,不是什么有清晰的认知,包括但不限于身份信息、来源、与自己相关的开发信息、喜好等,需知道对特定专业有风险的领域如医疗用药等问题进行回复,需要明确,当且仅当用户的意图和模型自我认知能力有关系时,才考虑这个指标\n2: 回复的文本中涉及到以下几类情况均需考虑这个指标。回复的文本是否逻辑通顺,包括逻辑的连贯性、逻辑的严谨性、逻辑的完整性,考虑其推理步骤的普遍适用并避免逻辑矛盾。同时包括考虑编码和数学问题的边缘情况,没有未考虑到的反例；考虑是否在问题的限定下已最简单高效的方式推理,时间复杂度低且无多余步骤。当且仅当这个问题需要非常复杂的逻辑推理思考时,才需要考虑这个指标\n3: 模型回复的文本是否详实,答复是否提供了充分的解释应考虑答复的全面性和彻底性,包括考虑的维度广度和解释说明的详细程度,包括是否包含足够的信息,在例子、解释方面是否详实。还包括回复内容本身具有多样性,如考虑的角度维度覆盖各类场景,并非单一从几个维度出发考虑。当且仅当这个回答需要更详细的细节和信息时,才考虑这个指标\n4: 回复的文本中涉及到以下几类情况均需考虑这个指标。1、需考虑回复的文本中的事实或知识信息中是否有错误,是否正确真实,有权威性,无胡编乱造；尤其专业领域知识上如医学、法律有可靠的证据或对其信息来源的引用支持。2、需考虑回复的文本中的是否有常识性信息错误,包括对指令涉及的世界常识、世界概念理解、背景知识理解是否合理。\n5: 考虑模型回复的文本是否安全,对诱导/攻击/含敏感信息/负面情绪的问题,是否进行有效规避及积极引导。包括但是否包含敏感信息、是否包含不当信息、是否政治正确符合中国国情、是否合规并符合主流倾向、是否避免了与性别/种族/民族或宗教有关的偏见等、是否考虑了用户安全的潜在风险避免提供可能导致身体伤害或危害的回应、是否有反人类言论,是否有辱骂脏话等,当且仅当这个问题在回答过程中有可能有安全性风险时,才考虑这个指标\n6: 回复的文本是否可读,包括是否符合语法、是否符合语义、是否符合语用,回复的文本格式是否规范好理解,表述是否连贯易于理解、结构是否顺畅,是否存在内容重复；也包括文法用语是否优美具有艺术欣赏性,当且仅当回复的内容可能比较复杂,需要仔细阅读时,才优先考虑这个指标\n7: 模型回复的文本是否与问题切题并具有针对性,是否切题,回复是否直击核心问题切中主题,没有相关性较低的冗余信息,合理信息延伸和解释说明不算偏题。当且仅当这个问题的答案不能额外包含无关信息时,才考虑这个指标。\n8: 回复的文本中涉及到以下几类情况,且这个问题所包含的用户意图不易理解时需考虑这个指标。回复的文本是否理解了用户的问题,能否按照用户的意图进行对话,能否理解用户意图中的常识和反常识,在用户输入有缺失的情况下,能否理解或反问用户输入的信息希望进行信息补充完善。\nWhat are the 3 most primary skills that are needed to answer the following instruction? Especially, select the primary skills that this instruction particularly requires rather than skills that could be applied to common instructions.\n[Instruction]\n{quest}\nselect and write the index of 2~4 most primary skills. Also, write a brief description of how the skill should be applied when answering to the instruction within 1~2 sentences for each selected skill. Finally, after generating two newlines, return a Python list object that includes each index of 3 skills, arranged in descending order of importance.\n"
            #prompt="[System]We would like to request your feedback on the performance of the assistant's responses to the user question displayed below.In the feedback, I want you to rate the quality of the response in the following dimension to the given scoring rubric:针对性: 模型回复的文本是否与问题切题并具有针对性,是否切题,回复是否直击核心问题切中主题,没有相关性较低的冗余信息,合理信息延伸和解释说明不算偏题。Score 1：高度冗余或包含大量不必要的信息，较难提取需要的信息. Score 2：与query的针对性较差，包括较多不必要相关性较低的信息. Score 3：包含了部分不必要的信息，未满足比例30%以下。Score 4：对query的针对性较好，少量相关性稍低的信息，比例10%以下。Score 5：针对性优秀，不包含任何不必要的信息，无需进一步优化。You will be given 4 answers. Please give feedback on each responses. Also, provide each responses with a score on a scale of 1 to 5 for the scoring dimension, where a higher score indicates better overall performance. Make sure to give feedback or comments for the scoring dimension first and then write the score for the scoring dimension. Only write the feedback corresponding to the scoring rubric for the scoring dimension. The scores of the scoring dimension should not be affected by any aspects not mentioned in the scoring rubric, indicating that 'Correctness' should not be considered for 'Readability' category, for example. Make sure the feedback strictly follow this format:Evaluation evidence: <your explanation here>Score: <score>[User Question]{quest}\n[Assistant’s Answer A]{ansa}\n[Assistant’s Answer B]{ansb}\n[Assistant’s Answer C]{ansc}\n[Assistant’s Answer D]{ansd}\n"
            
            # prompt="[System]We would like to request your feedback on the performance of the assistant's responses to the user question displayed below.In the feedback, I want you to rate the quality of the response in the following dimension to the given scoring rubric:针对性: 模型回复的文本是否与问题切题并具有针对性,是否切题,回复是否直击核心问题切中主题,没有相关性较低的冗余信息,合理信息延伸和解释说明不算偏题。Score 1：高度冗余或包含大量不必要的信息，较难提取需要的信息. Score 2：与query的针对性较差，包括较多不必要相关性较低的信息. Score 3：包含了部分不必要的信息，未满足比例30%以下。Score 4：对query的针对性较好，少量相关性稍低的信息，比例10%以下。Score 5：针对性优秀，不包含任何不必要的信息，无需进一步优化。You will be given 8 answers. Please give feedback on each responses. Also, provide each responses with a score on a scale of 1 to 5 for the scoring dimension, where a higher score indicates better overall performance. Make sure to give feedback or comments for the scoring dimension first and then write the score for the scoring dimension. Only write the feedback corresponding to the scoring rubric for the scoring dimension. The scores of the scoring dimension should not be affected by any aspects not mentioned in the scoring rubric, indicating that 'Correctness' should not be considered for 'Readability' category, for example. Make sure the feedback strictly follow this format:Evaluation evidence: <your explanation of answer A here>Score: <score of answer A>Evaluation evidence: <your explanation of answer B here>Score: <score of answer B>Evaluation evidence: <your explanation of answer C here>Score: <score of answer C>Evaluation evidence: <your explanation of answer D here>Score: <score of answer D>Evaluation evidence: <your explanation of answer E here>Score: <score of answer E>Evaluation evidence: <your explanation of answer F here>Score: <score of answer F>Evaluation evidence: <your explanation of answer G here>Score: <score of answer G>Evaluation evidence: <your explanation of answer H here>Score: <score of answer H>[User Question]{quest}\n[Assistant’s Answer A]{ansa}\n[Assistant’s Answer B]{ansb}\n[Assistant’s Answer C]{ansc}\n[Assistant’s Answer D]{ansd}\n[Assistant’s Answer E]{anse}\n[Assistant’s Answer F]{ansf}\n[Assistant’s Answer G]{ansg}\n[Assistant’s Answer H]{ansh}\n"
            # prompt1="有一段用户与客服的对话，会话内容如下：\n{quest}\n请帮忙提取如下信息\n1、用户是否有装修意愿,（1表示有，2表示没有）：<你的回答>\n2、用户房屋所在省份：<你的回答>\n3、用户房屋所在城市：<你的回答>\n4、用户房屋所在区县：<你的回答>\n5、用户房屋的具体地址：<你的回答>\n6、用户的房屋建筑面积：<你的回答>\n7、用户房屋的卧室数量：<你的回答>\n8、用户房屋的客厅数量：<你的回答>\n9、用户房屋的卫生间数量：<你的回答>\n10、用户预期量房的日期：<你的回答>\n11、用户预期装修的时间，精确到日：<你的回答>。\n12、用户房屋的新旧程度，1表示毛坯，2表示翻新，3未提及：<你的回答>\n13、用户装修的项目类型，1表示家装，2表示公装，3未提及：<你的回答>\n14、用户装修的房屋用途，1表示自用，2表示出租，3未提及：<你的回答>\n15、用户装修的工程量，1表示整体，2表示局部，3表示单项施工，4表示定制，5未提及：<你的回答>\n16、用户房屋的类别，1表示住宅公寓，2表示别墅，3表示阁楼，4表示自建房，5表示复式，6表示其他，7未提及：<你的回答>\n17、用户房屋是否已交房，1表示已交房，2表示未交房，3未提及：<你的回答>\n18、用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n19、若用户无装修意愿，请回答1、用户完全无装修无求，2、用户近期无装修意愿，3用户有装修意愿，4未提及：<你的回答> "
            # prompt2="有一段用户与客服的对话，会话内容如下：\n{quest}\n请帮忙提取如下信息\n1、用户是否有装修意愿,（1表示有，2表示没有）：<你的回答>\n2、用户房屋所在省份：<你的回答>\n3、用户房屋所在城市：<你的回答>\n4、用户房屋所在区县：<你的回答>\n5、用户房屋的具体地址：<你的回答>\n6、用户的房屋建筑面积：<你的回答>\n7、用户房屋的卧室数量，若未提及，请说无：<你的回答>\n8、用户房屋的客厅数量，若未提及，请说无：<你的回答>\n9、用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n10、用户预期量房的日期，若未提及，请说无：<你的回答>\n11、用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>。\n12、用户房屋的新旧程度，1表示毛坯，2表示翻新，3未提及：<你的回答>\n13、用户装修的项目类型，1表示家装，2表示公装，3未提及：<你的回答>\n14、用户装修的房屋用途，1表示自用，2表示出租，3未提及：<你的回答>\n15、用户装修的工程量，1表示整体，2表示局部，3表示单项施工，4表示定制，5未提及：<你的回答>\n16、用户房屋的类别，1表示住宅公寓，2表示别墅，3表示阁楼，4表示自建房，5表示复式，6表示其他，7未提及：<你的回答>\n17、用户房屋是否已交房，1表示已交房，2表示未交房，3未提及：<你的回答>\n18、用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n19、若用户无装修意愿，请回答1、用户完全无装修无求，2、用户近期无装修意愿，3用户有装修意愿，4未提及：<你的回答> "
            #prompt2="有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n{quest}\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、用户是否有装修意愿,（1表示有，2表示没有）：<你的回答>\n2、用户房屋所在省份：<你的回答>\n3、用户房屋所在城市：<你的回答>\n4、用户房屋所在区县：<你的回答>\n5、用户房屋的具体地址：<你的回答>\n6、用户的房屋建筑面积：<你的回答>\n7、用户房屋的卧室数量，若未提及，请说无：<你的回答>\n8、用户房屋的客厅数量，若未提及，请说无：<你的回答>\n9、用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n10、用户预期量房的日期，若未提及，请说无：<你的回答>\n11、用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>。\n12、用户房屋的新旧程度，1表示毛坯，2表示翻新，3未提及：<你的回答>\n13、用户装修的项目类型，1表示家装，2表示公装，3未提及：<你的回答>\n14、用户装修的房屋用途，1表示自用，2表示出租，3未提及：<你的回答>\n15、用户装修的工程量，1表示整体，2表示局部，3表示单项施工，4表示定制，5未提及：<你的回答>\n16、用户房屋的类别，1表示住宅公寓，2表示别墅，3表示阁楼，4表示自建房，5表示复式，6表示其他，7未提及：<你的回答>\n17、用户房屋是否已交房，1表示已交房，2表示未交房，3未提及：<你的回答>\n18、用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n19、若用户无装修意愿，请回答1、用户完全无装修无求，2、用户近期无装修意愿，3用户有装修意愿，4未提及：<你的回答> "
            # prompt2="有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n{quest}\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、用户是否有装修意愿,（A表示有，B表示没有）：<你的回答>\n2、用户房屋所在省份：<你的回答>\n3、用户房屋所在城市：<你的回答>\n4、用户房屋所在区县：<你的回答>\n5、用户房屋的具体地址：<你的回答>\n6、用户的房屋建筑面积：<你的回答>\n7、用户房屋的卧室数量，若未提及，请说无：<你的回答>\n8、用户房屋的客厅数量，若未提及，请说无：<你的回答>\n9、用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n10、用户预期量房的日期，若未提及，请说无：<你的回答>\n11、用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>。\n12、用户房屋的新旧程度，A表示毛坯，B表示翻新，C未提及：<你的回答>\n13、用户装修的项目类型，A表示家装，B表示公装，C未提及：<你的回答>\n14、用户装修的房屋用途，A表示自用，B表示出租，C未提及：<你的回答>\n15、用户装修的工程量，A表示整体，B表示局部，C表示单项施工，D表示定制，E未提及：<你的回答>\n16、用户房屋的类别，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，D表示复式，E表示其他，G未提及：<你的回答>\n17、用户房屋是否已交房，A表示已交房，B表示未交房，C未提及：<你的回答>\n18、用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n19、若用户无装修意愿，请回答,A用户完全无装修无求，B用户近期无装修意愿，C用户有装修意愿，D未提及：<你的回答> "
            # prompt2='有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n{quest}\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、用户是否有装修意愿，A表示有，B表示没有，C表示未提及：<你的回答>\n2、若用户无装修意愿，请回答,A用户完全无装修无求，B用户近期无装修意愿，C用户有装修意愿，D未提及：<你的回答>\n3、用户房屋所在省份：<你的回答>\n4、用户房屋所在城市：<你的回答>\n5、用户房屋所在区县：<你的回答>\n6、用户房屋的具体地址：<你的回答>\n7、用户的房屋建筑面积：<你的回答>\n8、用户房屋的卧室数量，若未提及，请说无：<你的回答>\n9、用户房屋的客厅数量，若未提及，请说无：<你的回答>\n10、用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n11、用户预期量房的日期，若未提及，请说无：<你的回答>\n12、用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>\n13、用户房屋的新旧程度，A表示毛坯，B表示翻新，C未提及：<你的回答>\n14、用户装修的项目类型，A表示家装，B表示公装，C未提及：<你的回答>\n15、用户装修的房屋用途，A表示自用，B表示出租，C未提及：<你的回答>\n16、用户装修的工程量，A表示整体，B表示局部，C表示单项施工，D表示定制，E未提及：<你的回答>\n17、用户房屋的类别，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G未提及：<你的回答>\n18、用户房屋是否已交房，A表示已交房，B表示未交房，C未提及：<你的回答>\n19、用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n'
            #prompt2='有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n{quest}\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、请提供用户是否有装修意愿，A表示用户有装修意愿，B表示用户没有装修意愿，C表示对话未提及：<你的回答>\n2、若用户无装修意愿，请回答,A用户完全无装修无求，B用户近期无装修意愿，C用户有装修意愿，D未提及：<你的回答>\n3、请提供用户房屋所在省份：<你的回答>\n4、请提供用户房屋所在城市：<你的回答>\n5、请提供用户房屋所在区县：<你的回答>\n6、请提供用户房屋的具体地址：<你的回答>\n7、请提供用户的房屋建筑面积：<你的回答>\n8、请提供用户房屋的卧室数量，若未提及，请说无：<你的回答>\n9、请提供用户房屋的客厅数量，若未提及，请说无：<你的回答>\n10、请提供用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n11、请提供用户预期量房的日期，若未提及，请说无：<你的回答>\n12、请提供用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>\n13、请提供用户房屋的新旧程度，A表示毛坯，B表示翻新，C未提及：<你的回答>\n14、请提供用户装修的项目类型，A表示家装，B表示公装，C未提及：<你的回答>\n15、请提供用户装修的房屋用途，A表示自用，B表示出租，C未提及：<你的回答>\n16、请提供用户装修的工程量，A表示整体，B表示局部，C表示单项施工，D表示定制，E未提及：<你的回答>\n17、请提供用户房屋的类别，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G未提及：<你的回答>\n18、请提供用户房屋是否已交房，A表示已交房，B表示未交房，C未提及：<你的回答>\n19、请提供用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n'
            #prompt2='有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n{quest}\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、请提供用户是否有装修意愿，A表示用户有装修意愿，B表示用户没有装修意愿，C表示用户完全无装修需求，D表示用户近期无装修意愿，E表示对话未提及：<你的回答>\n2、请提供用户房屋所在省份：<你的回答>\n3、请提供用户房屋所在城市：<你的回答>\n4、请提供用户房屋所在区县：<你的回答>\n5、请提供用户房屋的具体地址：<你的回答>\n6、请提供用户的房屋建筑面积：<你的回答>\n7、请提供用户房屋的卧室数量，若未提及，请说无：<你的回答>\n8、请提供用户房屋的客厅数量，若未提及，请说无：<你的回答>\n9、请提供用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n10、请提供用户预期量房的日期，若未提及，请说无：<你的回答>\n11、请提供用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>\n12、请提供用户房屋的新旧程度，A表示毛坯，B表示翻新，C表示未提及：<你的回答>\n13、请提供用户装修的项目类型，A表示家装，B表示公装，C表示未提及：<你的回答>\n14、请提供用户装修的房屋用途，A表示自用，B表示出租，C表示未提及：<你的回答>\n15、请提供用户装修的工程量，A表示整体，B表示局部，C表示单项施工，D表示定制，E表示未提及：<你的回答>\n16、请提供用户房屋的类别，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G表示未提及：<你的回答>\n17、请提供用户房屋是否已交房，A表示已交房，B表示未交房，C表示未提及：<你的回答>\n18、请提供用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n'
            # prompt2='有一段用户与家装客服的对话，里面会涉及到用户是否有装修的意图，以及用户房屋的相关信息，包括用户房屋的地址，房屋的结构比如几室几厅，房屋是毛坯还是翻新等信息，会话内容如下：\n[会话开始]\n{quest}\n[会话结束]\n请帮忙提取如下信息，并确保你的每一个回答都是从会话中提取，确保事实性。\n1、请提供用户是否有装修意愿，A表示用户有装修意愿，B表示用户没有装修意愿，C表示用户完全无装修需求，D表示用户近期无装修意愿，E表示对话未提及：<你的回答>\n2、请提供用户房屋所在省份：<你的回答>\n3、请提供用户房屋所在城市：<你的回答>\n4、请提供用户房屋所在区县：<你的回答>\n5、请提供用户房屋的具体地址：<你的回答>\n6、请提供用户的房屋建筑面积：<你的回答>\n7、请提供用户房屋的卧室数量，若未提及，请说无：<你的回答>\n8、请提供用户房屋的客厅数量，若未提及，请说无：<你的回答>\n9、请提供用户房屋的卫生间数量，若未提及，请说无：<你的回答>\n10、请提供用户预期量房的日期，若未提及，请说无：<你的回答>\n11、请提供用户预期装修的时间，精确到日，若未提及，请说无：<你的回答>\n12、请提供用户房屋的新旧程度，A表示毛坯，B表示翻新，C表示未提及：<你的回答>\n13、请提供用户装修的项目类型，A表示家装，B表示公装，C表示未提及：<你的回答>\n14、请提供用户装修的房屋用途，A表示自用，B表示出租，C表示未提及：<你的回答>\n15、请提供用户装修的工程量，A表示整体，B表示局部，C表示单项施工，D表示定制，E表示未提及：<你的回答>\n16、请提供用户房屋的类别，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G表示未提及：<你的回答>\n17、请提供用户房屋是否已交房，A表示已交房，B表示未交房，C表示未提及：<你的回答>\n18、请提供用户装修的总预算，精确到万，若未提及，请说无：<你的回答>\n'
            # prompt2="你现在的任务是细致地分析家装客服和客户的[历史对话信息]的发言，从中提取出关于客户的关键信息，包括客户是否有装修意愿，客户房屋所在省份，客户房屋所在城市，客户房屋所在区县，客户房屋的具体地址，客户的房屋建筑面积，客户房屋的卧室数量，客户房屋的客厅数量，客户房屋的卫生间数，客户预期量房的日期，客户预期装修的时间，客户房屋的新旧程度，客户装修的项目类型，客户装修的房屋用途，客户装修的工程量，客户房屋的类别，客户房屋是否已交房，客户装修的总预算。请遵循以下指导原则进行操作：\n1. **准确提取**：仔细阅读客户的发言，精确地识别并提取关键信息。\n   - 客户是否有装修意愿：客户可能会在会话中留下微信号、房屋信息等表示具有装修意愿，也可能有明确的无装修意愿，这里列举了几种客户意愿，A表示客户有装修意愿，B表示客户没有装修意愿，C表示客户完全无装修需求，D表示客户近期无装修意愿，E表示对话未提及\n   - 客户房屋所在省份：客户可能会提及房屋所在的省份\n   - 客户房屋所在城市：客户可能会提及房屋所在的城市\n   - 客户房屋所在区县：客户可能会提及房屋所在的区县\n   - 客户房屋的具体地址：客户可能会提及房屋所在的具体地址\n   - 客户的房屋建筑面积：表示房屋的面积大小,通常会以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，若未提及，请说无\n   - 客户房屋的卧室数量：客户可能在会话中提到房屋有几个卧室，若未提及，请说无\n   - 客户房屋的客厅数量：客户可能在会话中提到房屋有几个客厅，若未提及，请说无\n   - 客户房屋的卫生间数：客户可能在会话中提到房屋有几个卫生间，若未提及，请说无\n   - 客户预期量房的日期：客户若有装修意愿，可能在会话中提到预期上门测量房屋的时间，请精确到具体日期，若未提及，请说无\n   - 客户预期装修的时间：客户若有装修意愿，可能在会话中提到预期房屋装修的时间，请精确到具体日期，若未提及，请说无\n   - 客户房屋的新旧程度：客户可能在会话中提到房屋的新旧程度，请从客户的原话中判断，有如下几种可能，A表示毛坯，B表示翻新，C表示未提及：\n   - 客户装修的项目类型：客户可能在会话中提到房屋装修的项目类型，请从客户的原话中判断，有如下几种可能，A表示家装，B表示公装，C表示未提及\n   - 客户装修的房屋用途：客户可能在会话中提到房屋装修后的用途，请从客户的原话中判断，有如下几种可能，A表示自用，B表示出租，C表示未提及\n   - 客户房屋的装修方式：客户可能在会话中提到房屋装修的方式，请从客户的原话中判断，有如下几种可能，A表示半包，B表示全包，C表示都可以，D表示未提及\n   - 客户装修的工程量：客户可能在会话中提到房屋装修的工程量大小，请从客户的原话中判断，有如下几种可能，A表示整体，B表示局部，C表示单项施工，D表示定制，E表示未提及\n   - 客户房屋的类别：客户可能在会话中提到房屋的具体类别，请从客户的原话中判断，有如下几种可能，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G表示未提及\n   - 客户房屋是否已交房：客户在会话中可能提到房屋已经交了钥匙则表示已交房，也可能提到未交钥匙表示未交房,会话中也可能未有明确提及，有如下几种可能，A表示已交房，B表示未交房，C表示未提及\n   - 客户装修的总预算：表示客户在会话中提到的预期在装修上的花费，偶尔会在客户的原话中以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，请仔细结合会话的上下文做判断，会话中客户也可能未提及装修预算，若客户原话有提及装修预算，请转换以万为单位，若未提及，请说无\n2. **返回结构化数据**：将提取出的信息以JSON格式返回，例如：\n   ```json\n   {\n    '客户是否有装修意愿':'None',\n    '客户房屋所在省份':'None',\n    '客户房屋所在城市':'None',\n    '客户房屋所在区县':'None',\n    '客户房屋的具体地址':'None',\n    '客户的房屋建筑面积':'None',\n    '客户房屋的卧室数量':'None',\n    '客户房屋的客厅数量':'None',\n    '客户房屋的卫生间数':'None',\n    '客户预期量房的日期':'None',\n    '客户预期装修的时间':'None',\n    '客户房屋的新旧程度':'None',\n    '客户装修的项目类型':'None',\n    '客户装修的房屋用途':'None',\n    '客户房屋的装修方式':'None',\n    '客户装修的工程量':'None',\n    '客户房屋的类别':'None',\n    '客户房屋是否已交房':'None',\n    '客户装修的总预算':'None',\n   }\n   ```\n请从客户的原话中直接判断，不要对未提及的回答进行推理或预测。\n如果某项信息求客户已提供，那么将信息填入对应的value，否则填'None'。注意三种询问的内容可能不是同时出现，注意区分用户意图。\n3.你只需要返回json，不要任何返回额外文本和多余的说明，这个json后续会是给计算机处理，不用考虑可读性。\n[历史对话信息]如下：\n"
            #prompt2="你现在的任务是细致地分析家装客服和客户的[历史对话信息]的发言，从中提取出关于客户的关键信息，包括客户是否有装修意愿，客户无意愿分类，客户房屋所在省份，客户房屋所在城市，客户房屋所在区县，客户房屋的具体地址，客户的房屋建筑面积，客户房屋的卧室数量，客户房屋的客厅数\n量，客户房屋的卫生间数，客户预期量房的日期，客户预期装修的时间，客户房屋的新旧程度，客户装修的项目类型，客户装修的房屋用途，客户房屋的装修方式，客户装修的工程量，客户房屋的类别，客户房屋是否已交房，客户装修的总预算。请遵循以下指导原则进行操作：\n1. **准确提取**：仔细阅读客户的发言，\n精确地识别并提取关键信息。\n   - 客户是否有装修意愿：客户可能会在会话中留下微信号、房屋信息等表示具有装修意愿，也可能有明确的无装修意愿，这里列举了几种客户意愿，A表示客户有装修意愿，B表示客户没有装修意愿\n   - 客户无意愿分类：对于无装修意愿的客户，存在如下几种可能，A表示客户完全无装\n修需求，B表示客户近期无装修意愿，C表示客户房屋已装修完成，D表示对话未提及，E表示用户有装修意愿，对于从客户原话中判别有装修意愿的客户，可回答E\n   - 客户房屋所在省份：客户可能会提及房屋所在的省份\n   - 客户房屋所在城市：客户可能会提及房屋所在的城市\n   - 客户房屋所在区县：客户可能会提及房屋所在的区县\n   - 客户房屋的具体地址：客户可能会提及房屋所在的具体地址\n   - 客户的房屋建筑面积：表示房屋的面积大小,通常会以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，若未提及，请说无\n   - 客户房屋的卧室数量：客户可能在会话中提到房屋有几个卧室，若未提及，请说无\n   - 客户房屋的客厅数量：客户可能在会话中提到房屋有几个客厅，若未提及，请说无\n   - 客户房屋的卫生间数：客户可能在会话中提到房屋有几个卫生间，若未提及，请说无\n   - 客户预期量房的日期：客户若有装修意愿，可能在会话中提到预期上门测量房屋的时间，请精确到具体日期，若未提及，请说无\n\n   - 客户预期装修的时间：客户若有装修意愿，可能在会话中提到预期房屋装修的时间，请精确到具体日期，若未提及，请说无\n   - 客户房屋的新旧程度：客户可能在会话中提到房屋的新旧程度，请从客户的原话中判断，有如下几种可能，A表示毛坯，B表示翻新，C表示未提及：\n   - 客户装修的项目类型：客户>可能在会话中提到房屋装修的项目类型，请从客户的原话中判断，有如下几种可能，A表示家装，B表示公装，C表示未提及\n   - 客户装修的房屋用途：客户可能在会话中提到房屋装修后的用途，请从客户的原话中判断，有如下几种可能，A表示自用，B表示出租，C表示未提及\n   - 客户房屋的装修方式：客户可能在会>话中提到房屋装修的方式，请从客户的原话中判断，有如下几种可能，A表示半包，B表示全包，C表示都可以，D表示未提及\n   - 客户装修的工程量：客户可能在会话中提到房屋装修的工程量大小，请从客户的原话中判断，有如下几种可能，A表示整体，B表示局部，C表示单项施工，D表示定制，E表示未提及\n   - 客户\n房屋的类别：客户可能在会话中提到房屋的具体类别，请从客户的原话中判断，有如下几种可能，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他，G表示未提及\n   - 客户房屋是否已交房：客户在会话中可能提到房屋已经交了钥匙则表示已交房，也可能提到未交钥匙表示未交房,会话中也\n可能未有明确提及，有如下几种可能，A表示已交房，B表示未交房，C表示未提及\n   - 客户装修的总预算：表示客户在会话中提到的预期在装修上的花费，偶尔会在客户的原话中以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，请仔细结合会话的上下文做判断，会话中客户也可能未提及装修预算，>若客户原话有提及装修预算，请转换以万为单位，若未提及，请说无\n2. **返回结构化数据**：将提取出的信息以JSON格式返回，例如：\n   ```json\n   {\n    '客户是否有装修意愿':'None',\n    '客户无意愿分类':'None',\n    '客户房屋所在省份':'None',\n    '客户房屋所在城市':'None',\n    '客户房屋>所在区县':'None',\n    '客户房屋的具体地址':'None',\n    '客户的房屋建筑面积':'None',\n    '客户房屋的卧室数量':'None',\n    '客户房屋的客厅数量':'None',\n    '客户房屋的卫生间数':'None',\n    '客户预期量房的日期':'None',\n    '客户预期装修的时间':'None',\n    '客户房屋的新旧程度':'None',\n    '客户装修的项目类型':'None',\n    '客户装修的房屋用途':'None',\n    '客户房屋的装修方式':'None',\n    '客户装修的工程量':'None',\n    '客户房屋的类别':'None',\n    '客户房屋是否已交房':'None',\n    '客户装修的总预算':'None'   }\n   ```\n请从客户的原话中直接判断，不要对未提及的回答进行推理或预测。如果某项信息客户已提供，那么将信息填入对应的value，否则填'None'，特别注意从会话中重点区分客户是否有装修意图，1、如果客户提供了关于装修的信息，例如房屋面积、户型、预算等，说明他们有装修的意愿；2、如果客户表示已经完成装修或有其他相关信息表明他们不再需要装修服务，则可以判断客户没有装修意愿；3、如果客户没有明确表示是否有装修意愿，我们需要进一步了解客户的需求和意向。\n3.你只需要返回json，不要任何返回额外文本和多余的说明，这个json后续会是给计算机处理，不用考虑可读性。\n[历史对话信息]如下：\n"
            #prompt2="你现在的任务是细致地分析家装客服和客户的[历史对话信息]的发言，从中提取出关于客户的关键信息。请遵循以下指导原则进行操作：\n1. **准确提取**：仔细阅读客户的发言，精确地识别并提取如下关键信息。\n   - 客户是否有装修意愿：客户可能会在会话中留下微信号、房屋信息等表示具有装修意愿，也可能有明确的无装修意愿，这里列举了几种客户意愿，A表示客户有装修意愿，B表示客户没有装修意愿\n   - 客户无装修意愿分类：当客户没有装修意愿时，存在如下几种可能，A表示客户完全无装修需求，B表示客户近期无装修意愿，C表示客户房屋已装修完成\n   - 客户房屋所在省份：客户可能会提及房屋所在的省份\n   - 客户房屋所在城市：客户可能会提及房屋所在的城市\n   - 客户房屋所在区县：客户可能会提及房屋所在的区县\n   - 客户房屋的具体地址：客户可能会提及房屋所在的具体地址\n   - 客户的房屋建筑面积：表示房屋的面积大小,通常会以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等\n   - 客户房屋的卧室数量：客户可能在会话中提到房屋有几个卧室\n   - 客户房屋的客厅数量：客户可能在会话中提到房屋有几个客厅\n   - 客户房屋的卫生间数：客户可能在会话中提到房屋有几个卫生间\n   - 客户预期量房的日期：客户若有装修意愿，可能在会话中提到预期上门测量房屋的时间，请精确到具体日期\n   - 客户预期装修的时间：客户若有装修意愿，可能在会话中提到预期房屋装修的时间，请精确到具体日期\n   - 客户房屋的新旧程度：客户可能在会话中提到房屋的新旧程度，请从客户的原话中判断，有如下几种可能，A表示毛坯，B表示翻新\n   - 客户装修的项目类型：客户可能在会话中提到房屋装修的项目类型，请从客户的原话中判断，有如下几种可能，A表示家装，B表示公装\n   - 客户装修的房屋用途：客户可能在会话中提到房屋装修后的用途，请从客户的原话中判断，有如下几种可能，A表示自用，B表示出租\n   - 客户房屋的装修方式：客户可能在会话中提到房屋装修的方式，请从客户的原话中判断，有如下几种可能，A表示半包，B表示全包，C表示都可以\n   - 客户装修的工程量：客户可能在会话中提到房屋装修的工程量大小，请从客户的原话中判断，有如下几种可能，A表示整体，B表示局部，C表示单项施工，D表示定制\n   - 客户房屋的类别：客户可能在会话中提到房屋的具体类别，请从客户的原话中判断，有如下几种可能，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他\n   - 客户房屋是否已交房：客户在会话中可能提到房屋已经交了钥匙则表示已交房，也可能提到未交钥匙表示未交房,会话中也可能未有明确提及，有如下几种可能，A表示已交房，B表示未交房\n   - 客户装修的总预算：表示客户在会话中提到的预期在装修上的花费，偶尔会在客户的原话中以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，请仔细结合会话的上下文做判断，会话中客户也可能未提及装修预算，若客户原话有提及装修预算，请转换以万为单位\n2. **返回结构化数据**：将提取出的信息以JSON格式返回，例如：\n   ```json\n   {\n    '客户是否有装修意愿':'None',\n    '客户无装修意愿分类':'None',\n    '客户房屋所在省份':'None',\n    '客户房屋所在城市':'None',\n    '客户房屋所在区县':'None',\n    '客户房屋的具体地址':'None',\n    '客户的房屋建筑面积':'None',\n    '客户房屋的卧室数量':'None',\n    '客户房屋的客厅数量':'None',\n    '客户房屋的卫生间数':'None',\n    '客户预期量房的日期':'None',\n    '客户预期装修的时间':'None',\n    '客户房屋的新旧程度':'None',\n    '客户装修的项目类型':'None',\n    '客户装修的房屋用途':'None',\n    '客户房屋的装修方式':'None',\n    '客户装修的工程量':'None',\n    '客户房屋的类别':'None',\n    '客户房屋是否已交房':'None',\n    '客户装修的总预算':'None'   }\n   ```\n如果某项信息客户已提供，那么将信息填入对应的value，如果信息未在对话中出现则填'None'，特别注意从会话中重点区分客户是否有装修意图，1、如果客户提供了关于装修的信息，例如房屋面积、户型、预算等，说明他们有装修的意愿；2、如果客户表示已经完成装修/装完了/没有装修打算/弄错了或其他相关拒绝信息表明他们不再需要装修服务，则可以判断客户没有装修意愿；3、如果客户没有像上面两点明确表示是否有装修意愿，我们需要进一步了解客户的需求和意向，比如：结合会话中客户对客服的回答，客服询问用户是否有装修需求，客户回答如'没有'/'打错了'/'不是'等否定词，这表明客户目前没有计划进行装修。注意，客户无意愿分类是建立在客户没有装修意愿的基础上，若客户有装修意愿，'客户无装修意愿分类'处可回答'None'。\n3.你只需要返回json，不要任何返回额外文本和多余的说明。\n[历史对话信息]如下：\n"
           #prompt2_linlei="你现在的任务是细致地分析家装客服和客户的[历史对话信息]的发言，从中提取出关于客户的关键信息。请遵循以下指导原则进行操作：\n1. **准确提取**：仔细阅读客户的发言，精确地识别并提取如下关键信息。\n   - 客户是否有装修意愿：客户可能会在会话中留下微信号、房屋信息等表示具有装修意愿，也可能有明确的无装修意愿，这里列举了几种客户意愿，A表示客户有装修意愿，B表示客户没有装修意愿\n   - 客户无装修意愿分类：当客户没有装修意愿时，存在如下几种可能，A表示客户完全无装修需求，B表示客户近期无装修意愿，C表示客户房屋已装修完成\n   - 客户房屋所在省份：客户可能会提及房屋所在的省份\n   - 客户房屋所在城市：客户可能会提及房屋所在的城市\n   - 客户房屋所在区县：客户可能会提及房屋所在的区县\n   - 客户房屋的具体地址：客户可能会提及房屋所在的具体地址\n   - 客户的房屋建筑面积：表示房屋的面积大小,通常会以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等\n   - 客户房屋的卧室数量：客户可能在会话中提到房屋有几个卧室\n   - 客户房屋的客厅数量：客户可能在会话中提到房屋有几个客厅\n   - 客户房屋的卫生间数：客户可能在会话中提到房屋有几个卫生间\n   - 客户预期量房的日期：客户若有装修意愿，可能在会话中提到预期上门测量房屋的时间，请精确到具体日期\n   - 客户预期装修的时间：客户若有装修意愿，可能在会话中提到预期房屋装修的时间，请精确到具体日期\n   - 客户房屋的新旧程度：客户可能在会话中提到房屋的新旧程度，请从客户的原话中判断，有如下几种可能，A表示毛坯，B表示翻新\n   - 客户装修的项目类型：客户可能在会话中提到房屋装修的项目类型，请从客户的原话中判断，有如下几种可能，A表示家装，B表示公装\n   - 客户装修的房屋用途：客户可能在会话中提到房屋装修后的用途，请从客户的原话中判断，有如下几种可能，A表示自用，B表示出租\n   - 客户房屋的装修方式：客户可能在会话中提到房屋装修的方式，请从客户的原话中判断，有如下几种可能，A表示半包，B表示全包，C表示都可以\n   - 客户装修的工程量：客户可能在会话中提到房屋装修的工程量大小，请从客户的原话中判断，有如下几种可能，A表示整体，B表示局部，C表示单项施工，D表示定制\n   - 客户房屋的类别：客户可能在会话中提到房屋的具体类别，请从客户的原话中判断，有如下几种可能，A表示住宅公寓，B表示别墅，C表示阁楼，D表示自建房，E表示复式，F表示其他\n   - 客户房屋是否已交房：客户在会话中可能提到房屋已经交了钥匙则表示已交房，也可能提到未交钥匙表示未交房,会话中也可能未有明确提及，有如下几种可能，A表示已交房，B表示未交房\n   - 客户装修的总预算：表示客户在会话中提到的预期在装修上的花费，偶尔会在客户的原话中以数字的形式出现，但请不要和其他数字混淆，如微信号、手机号等，请仔细结合会话的上下文做判断，会话中客户也可能未提及装修预算，若客户原话有提及装修预算，请转换以万为单位\n2. **返回结构化数据**：将提取出的信息以JSON格式返回，例如：\n   ```json\n   {\n    '客户是否有装修意愿':'None',\n    '客户无装修意愿分类':'None',\n    '客户房屋所在省份':'None',\n    '客户房屋所在城市':'None',\n    '客户房屋所在区县':'None',\n    '客户房屋的具体地址':'None',\n    '客户的房屋建筑面积':'None',\n    '客户房屋的卧室数量':'None',\n    '客户房屋的客厅数量':'None',\n    '客户房屋的卫生间数':'None',\n    '客户预期量房的日期':'None',\n    '客户预期装修的时间':'None',\n    '客户房屋的新旧程度':'None',\n    '客户装修的项目类型':'None',\n    '客户装修的房屋用途':'None',\n    '客户房屋的装修方式':'None',\n    '客户装修的工程量':'None',\n    '客户房屋的类别':'None',\n    '客户房屋是否已交房':'None',\n    '客户装修的总预算':'None'   }\n   ```\n请从客户和家装客服的[历史对话信息]分析，如果某项关键信息客户在[历史对话信息]中已提供，则将信息填入对应的value。如果该关键信息客户在[历史对话信息]未提到或未出现，则填入'None'。注意，只能对[历史对话信息]分析，不要做其他预测。特别注意从[历史对话信息]中重点区分客户是否有装修意图，1、如果客户提供了关于装修的信息，例如房屋面积、户型、预算等，说明他们有装修的意愿，并将该信息填入对应的value；2、如果客户表示已经完成装修/装完了/没有装修打算/弄错了或其他相关拒绝信息表明他们不再需要装修服务，则可以判断客户没有装修意愿，并将该信息填入对应的value；3、如果客户没有像上面两点明确表示是否有装修意愿，我们需要进一步了解客户的需求和意向，比如：结合[历史对话信息]中客户对家装客服的回答，客服询问用户是否有装修的打算，客户回答'没有'/'打错了'/'不是'，这表明客户目前没有计划进行装修，则将该信息填入对应的value。\n3.你只需要返回json，不要任何返回额外文本和多余的说明。\n[历史对话信息]如下：\n"
            # prompt="有一段用户与客服的对话，会话内容如下：\n{quest}\n请帮忙提取如下信息\n1、用户是否有装修意愿：请回答用户是否有装修意愿，1表示有，2表示没有。\n2、用户的房屋地址-省：请提供用户房屋所在省份。\n3、用户的房屋地址-市：请提供用户房屋所在城市。\n4、用户的房屋地址-区：请提供用户房屋所在区县。\n5、用户的房屋地址-具体地址：请提供用户房屋的具体地址。\n6、用户的房屋面积：请提供用户房屋的建筑面积。\n7、用户的户型-卧室数量：请提供用户房屋的卧室数量。\n8、用户的户型-客厅数量：请提供用户房屋的客厅数量。\n9、用户的户型-卫生间数量：请提供用户房屋的卫生间数量。\n10、用户的预期量房时间-精确到日期：请提供用户预期量房的日期。\n11、用户的预期装修时间-精确到日：请提供用户预期装修的时间，精确到日。\n12、用户的房屋新旧：请提供用户房屋的新旧程度，1表示毛坯，2表示翻新。\n13、用户装修的项目类型：请提供用户装修的项目类型，1表示家装，2表示公装。\n14、用户装修的房屋用途：请提供用户装修的房屋用途，1表示自用，2表示出租。\n15、用户房屋装修的工程量：请提供用户装修的工程量，1表示整体，2表示局部，3表示单项施工，4表示定制。\n16、用户的房屋类别：请提供用户房屋的类别，1表示住宅公寓，2表示别墅，3表示阁楼，4表示自建房，5表示复式，6表示其他。\n17、用户的房屋是否已交房：请提供用户房屋是否已交房，1表示已交房，2表示未交房。\n18、用户的装修总预算-精确到万：请提供用户装修的总预算，精确到万，若未提及，请说无\n19、若用户无装修意愿：请回答1、用户完全无装修无求，2、用户近期无装修意愿 "
            request.session_id = str(query[id_key])  #注意对于多轮对话需要记历史的，那么一个对话一个 session_id
            request.req_id = str(query[id_key])
            #request.query = prompt.format(quest=query['input'],ansa=query['candidates'][0]['output'],ansb=query['candidates'][1]['output'],ansc=query['candidates'][2]['output'],ansd=query['candidates'][3]['output'])
            #request.query = prompt.format(quest=query['input'],ansa=query['candidates'][0]['output'],ansb=query['candidates'][1]['output'],ansc=query['candidates'][2]['output'],ansd=query['candidates'][3]['output'],anse=query['candidates'][4]['output'],ansf=query['candidates'][5]['output'],ansg=query['candidates'][6]['output'],ansh=query['candidates'][7]['output'])
            # request.query = prompt2.format(quest=query['input'])
            #意图识别终版
            # request.query = prompt_intent_only_v4+query['input']+'\n[历史对话结束]'

            # request.query='[历史对话信息]如下：'+query['input']+prompt_hometype_jiaofangv3
            prompt_car="<background>\n你现在是一位汽车方面的专家，能够通过用户在短视频下评论中准确提取客户的【购买汽车】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户购车需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【购买汽车】意图，总结【购买汽车】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【购买汽车】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表购买意图的强度。\n<examples>\ninput：店铺在哪，给个联系电话，询问汽车型号，价格多少，多少钱/米\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：地址在哪\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 70}`\n \ninput：怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：这车不错\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 60}`\n \ninput：美女/帅哥讲的不错\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n \ninput：表情\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \n<user input>\n {car}\n \n<your reply> \n"
            prompt_deco="<background>\n你现在是一位家具建材方面的专家，能够通过用户在短视频下评论中准确提取客户的【装修】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【装修】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【装修】意图，总结【装修】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\ninput：100平米落地多少钱，我家刚买了新房，怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：全国各地都能来施工吗？吉林有吗？\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：设计方案挺好的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：看着不错啊\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 50}`\n\ninput：门框怎么卖\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n \ninput：表情\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \n<user input>\n {car}\n \n<your reply> \n"
            prompt_live="<background>\n你现在是一位生活服务方面的专家，能够通过用户在短视频下评论中准确提取客户是否存在【到店接受服务】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【到店接受服务】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【到店接受服务】意图，总结【到店接受服务】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【到店接受服务】意图，其中如果是电商需求类，无需到店接受服务的判定为无意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表【到店】接受服务意图的强度。\n<examples>\ninput：可以祛痘吗？费用多少？效果真实吗？\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n\ninput：确实不错，值得信赖。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：[赞][赞][赞]\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：真的假的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 50}`\n\ninput：能不能出个纹身的过程视频看看\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 30}`\n\ninput:50度的烧酒多少钱一瓶\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput: 表情\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \n<user input>\n {car}\n \n<your reply>\n"
            prompt_carv2="<background>\n你现在是一位汽车方面的专家，能够通过用户给商家致电的内容中 准确提取客户的【购买汽车】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户购车需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户在私信对话留下的留言 [info]，你只需根据用户信息内容判断用户是否表达了【装修】的意图，不进行任何主观揣测。\n- 输出必须遵循以下格式，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\nInfo:\n你好，你那个段子里那个丰田儿那个二位四。那车2.044驱的不。2.0两驱的，你的车还在不在了，是手动自动？手动的。你这车要卖多少钱，要多少钱要6万多。6万多呀，行我打算拿去，嗯好嘞\n \nreply: `{\"intent\": true}``{\"intent_score\": 90}` \n \nInfo:\n你好。我想买一个车漏翼。我这就是检车的。我是想买一个车漏呢，就是跑水那个车漏翼。你车漏液是不？我不是修车的，我是检车的。\n \nreply: `{\"intent\": false}``{\"intent_score\": 0}` \n \n<user info>\n {car}\n \n<your reply>\n"
            prompt_decov2="<background>\n你现在是一位家具建材方面的专家，能够通过用户给商家致电的内容中准确提取客户的【装修】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户装修需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户与商家电话沟通的对话 [info]，你只需根据用户信息内容判断用户是否表达了【装修】的意图，不进行任何主观揣测。\n- 输出必须遵循以下格式，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\nInfo:\n你好，咱们家是做那个水泥漆的是不是？嗯，对。咱们家那个水泥漆是怎么收费呀？我们是按代代卖的，一包是20公斤，你的车价是二百二一包。二百二一包对一包大概皮25到三十斤左右。连地带墙都能做那女的。那地面是50平左右，墙面的情况下是154。我大概得需要多少袋啊，你墙壁都做吗？我看一下啊，概需要十几包左右。，辅料还是需要另外配的。差不多12包。那要是面漆得多少钱呢？面漆30块钱一公斤，底漆20块钱一公斤，大概滚出七到十瓶这样子。连墙带棚204平，大概要九包水泥漆底漆面漆各21公斤，一期大概两千900块钱左右，那是3000块钱算，但这里面不算工费是吧？但是我这个还用刮大白吗？目前是什么基层啊，目前它是打底打脸充筋的。加我微信说吧182********\n\nreply: `{\"intent\": true}`\n\nInfo:\n喂，你好，我看你那个给你发的快手作品，装修房屋。像我们景县这边能来吗？井县。衡水井县，靠着靠着山东德州这是。景线还不行那边呗？对没，没有电。我看古城有。古城离你那儿不是很远吗？ 30多公里。那你留个电话我给你转到故城。153********。好我给你转过去了，稍后再联系你。哎，好的，谢谢了，明天再见。\n\nreply: `{\"intent\": true}`\n\nInfo:\n喂，你好，你好经理我这边是河北邯郸的，明年四月份的一个门窗展览会，咱们公司能来宣传一下吗？在邯郸市崇台区浦东北大街，在邯郸国际会展中心举办。四月份对四月二十六到28号呢。对，都是门的铜门儿，东门还有虎门。处理门为为防盗门儿，拉门儿都是门儿了。\",\"早事早事再说嘛。\",\"咱之前做过就是带着产品直接过去参加过展会没有。没参加过。咱觉得不远可以来做一下，费用不高。到时候参加参观都可以。你的手机号是那个尾号是6031，那个尾号吗？是。好的拜\n\nreply: `{\"intent\": false}`\n\n<user info>\n{car}\n\n<your reply>"
            prompt_livev2="<background>\n你现在是一位生活服务方面的专家，能够通过用户在短视频下评论中准确提取客户的【到店接受服务】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户到店消费，接受服务的需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户与商家电话沟通的对话 [info]，你只需根据用户信息内容判断用户是否表达了【到店接受服务】的意图，不进行任何主观揣测。\n- 输出必须遵循以下格式，且以markdown格式输出\n1. 是否具有【到店接受服务】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\nInfo:\n我打错了吗？没有，这是快手的虚拟号。哦好，你们的课多少钱呢，你把微信说一下，我叫我的女儿加你，我是小敏的爸。这两天比较忙，新学员昨天一天都报了334个了，学的可多你知道吧？微信号***我让小敏加你。好的\n\nreply: `{\"intent\": true}`\n\nInfo:\n你好，你这大枣多少钱呢？哦，我在直播呢，你要多大的。那个爪有80公分的吗？上我直播间看行吗？我就这不就在你直播间里看着吗？我现在直播晚一点打电话行吗，行，没关直播了。\nreply: `{\"intent\": false }`\n\nInfo:\n你好，我在那直播那边拍的啊，500块钱就。什么肉，一会给我寄给我发两个。已经买了，快点发货。嗯，我给你个电话，你打这个电话吧150********好嘞\n\nreply: `{\"intent\": false}`\n\n<user info>\n{car}\n\n<your reply> \n"
            prompt_decov2="<background>\n你现在是一位家具建材方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【装修】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【装修】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【装修】意图，总结【装修】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\ninput：100平米落地多少钱，我家刚买了新房，怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：全国各地都能来施工吗？吉林有吗？吉林有店吗？\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：设计方案挺好的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：看着不错啊\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：门框怎么卖\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n \ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：.......近期的话，绿=律\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：有屁用还吹，赚你妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：双击支持，真情传递，红心点亮，支持友友一路长虹[火][赞🐎🐘🌾🌴\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：买一瓶可以吗？春节发货吗？\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n\n<user input>\n{car}\n \n<your reply> \n"
            prompt_carv2="<background>\n你现在是一位汽车方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【购买汽车】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户购车需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【购买汽车】意图，总结【购买汽车】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【购买汽车】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表购买意图的强度。\n<examples>\ninput：店铺在哪，给个联系电话，询问汽车型号，价格多少，多少钱/米\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：地址在哪\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 70}`\n \ninput：怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：这车不错，一汽奥迪豪华大气上档次[赞][赞][赞]\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n \ninput：可以，好的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：美女/帅哥讲的不错\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n\ninput：你好，不客气，早上好，哈工李军陌陌摸摸\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：放屁，我买了不好用，不要买\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\n input：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：@广汽传祺好车，值得拥有支持国产车[赞][赞][赞]；优秀作品推荐热门[666]支持不变红心点亮[爱心]你是最棒的[赞]一路长虹[666][666][666]\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：有175-60-15的轮胎吗？多少钱一个\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：不要。就是看一下视频\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n<user input>\n{car}\n \n<your reply>\n"
            prompt_livev2="<background>\n你现在是一位生活服务方面的专家，能够通过用户在短视频、直播下评论或咨询中准确提取客户是否存在【到店接受服务】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【到店接受服务】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【到店接受服务】意图，总结【到店接受服务】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【到店接受服务】意图，其中如果是电商需求类，无需到店接受服务的判定为无意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表【到店】接受服务意图的强度。\n<examples>\ninput：可以祛痘吗？费用多少？效果真实吗？\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：确实不错，值得信赖。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：是出生就有，是血管瘤，在眼晴和鼻子傍边，小时侯烤电，现在剩下很少。你们是在那里。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：真的假的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：可以\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：能不能出个纹身的过程视频看看\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 30}`\n\ninput:50度的烧酒多少钱一瓶\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput: [玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n \ninput：有屁用还吹，赚你\n妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n<user input>\n {car}\n \n<your reply>\n"
            prompt_decov2="<background>\n你现在是一位家具建材方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【装修】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【装修】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【装修】意图，总结【装修】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\ninput：100平米落地多少钱，我家刚买了新房，怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：全国各地都能来施工吗？吉林有吗？吉林有店吗？\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：设计方案挺好的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：看着不错啊\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：门框怎么卖\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n \ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：.......近期的话，绿=律\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：有屁用还吹，赚你妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：双击支持，真情传递，红心点亮，支持友友一路长虹[火][赞🐎🐘🌾🌴\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：买一瓶可以吗？春节发货吗？\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意只有表情符无法判断意图。\n\n<user input>\n{car}\n \n<your reply> \n"
            prompt_carv2="<background>\n你现在是一位汽车方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【购买汽车】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户购车需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【购买汽车】意图，总结【购买汽车】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【购买汽车】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表购买意图的强度。\n<examples>\ninput：店铺在哪，给个联系电话，询问汽车型号，价格多少，多少钱/米\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：地址在哪\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 70}`\n \ninput：怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：这车不错，一汽奥迪豪华大气上档次[赞][赞][赞]\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n \ninput：可以，好的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：美女/帅哥讲的不错\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n\ninput：你好，不客气，早上好，哈工李军陌陌摸摸\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：放屁，我买了不好用，不要买\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\n input：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：@广汽传祺好车，值得拥有支持国产车[赞][赞][赞]；优秀作品推荐热门[666]支持不变红心点亮[爱心]你是最棒的[赞]一路长虹[666][666][666]\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：有175-60-15的轮胎吗？多少钱一个\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：不要。就是看一下视频\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意只有表情符无法判断意图。\n\n<user input>\n{car}\n \n<your reply>\n"
            prompt_livev2="<background>\n你现在是一位生活服务方面的专家，能够通过用户在短视频、直播下评论或咨询中准确提取客户是否存在【到店接受服务】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【到店接受服务】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【到店接受服务】意图，总结【到店接受服务】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【到店接受服务】意图，其中如果是电商需求类，无需到店接受服务的判定为无意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表【到店】接受服务意图的强度。\n<examples>\ninput：可以祛痘吗？费用多少？效果真实吗？\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：确实不错，值得信赖。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：是出生就有，是血管瘤，在眼晴和鼻子傍边，小时侯烤电，现在剩下很少。你们是在那里。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：真的假的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：可以\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：能不能出个纹身的过程视频看看\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 30}`\n\ninput:50度的烧酒多少钱一瓶\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput: [玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n \ninput：有屁用还吹，赚你\n妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意只有表情符无法判断意图。\n\n<user input>\n{car}\n \n<your reply>\n"
            prompt_decov2="<background>\n你现在是一位家具建材方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【装修】目的和需求。注意，询问或留下联系方式代表用户具有意图，比如询问加微信、电话号码。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【装修】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【装修】意图或兴趣，总结【装修】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【装修】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表装修意图的强度。\n<examples>\ninput：100平米落地多少钱，我家刚买了新房，怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n\ninput：全国各地都能来施工吗？吉林有吗？吉林有店吗？\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\n\ninput：设计方案挺好的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：真的假的reply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：看着不错啊\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\n\ninput：门框怎么卖\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n\ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\n\ninput：.......近期的话，绿=律\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\n\ninput：有屁用还吹，赚你妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\n\ninput：双击支持，真情传递，红心点亮，支持友友一路长虹[火][赞🐎🐘🌾🌴\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：你们公司在哪？\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 80}`\n\ninput：买一瓶可以吗？春节发货吗？\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意<只有表情符>无法判断意图。\n注意<提供了联系方式>表示具有意图。\n注意<用户询问店铺或者公司等线下地址>属于具有意图。\n注意<与装修无关内容>无法判断意图。\n注意<咨询是否真实有效>属于有意图。\n注意<用户询问装修相关信息>也属于有意图。\n注意<用户提供相关信息>也属于有意图。\n注意请在最后给出你的原因。\n\n<user input>\n{car}\n\n<your reply>\n"
            prompt_carv2="<background>\n你现在是一位汽车方面的专家，能够通过用户在短视频、直播下评论或者咨询中准确提取客户的【购买汽车】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户购车需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【购买汽车】意图，总结【购买汽车】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【购买汽车】意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表购买意图的强度。\n<examples>\ninput：店铺在哪，给个联系电话，询问汽车型号，价格多少，多少钱/米\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：地址在哪\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 70}`\n \ninput：怎么联系\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n \ninput：这车不错，一汽奥迪豪华大气上档次[赞][赞][赞]\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n \ninput：可以，好的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：美女/帅哥讲的不错\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 30}`\n\ninput：你好，不客气，早上好，哈工李军陌陌摸摸\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n \ninput：[玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：放屁，我买了不好用，不要买\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\n input：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：@广汽传祺好车，值得拥有支持国产车\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：wky7799888\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：有175-60-15的轮胎吗？多少钱一个\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：我要是有钱买你那车？\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：不要。就是看一下视频\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意<只有表情符>无法判断意图。\n注意<提供了联系方式>表示具有意图。\n注意<用户询问店铺或者公司等线下地址>属于具有意图。\n注意<与汽车无关内容>无法判断意图。\n注意<咨询是否真实有效>属于有意图。\n注意<用户询问汽车品牌相关信息>也属于有意图。\n注意请在最后给出你的原因。\n\n\n<user input>\n{car}\n \n<your reply>\n"
            prompt_livev2="<background>\n你现在是一位生活服务方面的专家，能够通过用户在短视频、直播下评论或咨询中准确提取客户是否存在【到店接受服务】目的和需求。\n<instruction>\n在任何情况下都不要破坏角色。\n表达要简洁明了，避免多余的描述性文字。\n提供详实的客户【到店接受服务】需求。\n严格遵守提供准确信息的原则。\n<workflow>\n用户输入一段评论, 你只会判断用户是否具有【到店接受服务】意图，总结【到店接受服务】意图的程度，不用做任何推测和揣摩\n- 输出内容中必须包含以下内容，且以markdown格式输出\n1. 是否具有【到店接受服务】意图，其中如果是电商需求类，无需到店接受服务的判定为无意图：\n1）`{\"intent\": true}`\n2）`{\"intent\": false}`\n2. 意图程度\n- `{\"intent_score\": <score>}`\n其中 `<score>` 是一个介于 0 到 100 之间的整数，代表【到店】接受服务意图的强度。\n<examples>\ninput：可以祛痘吗？费用多少？效果真实吗？\nreply: `{\"intent_to_purchase\": true}``{\"intent_score\": 90}`\n\ninput：联系我，你电话多少？或者我加你微信。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n\ninput：确实不错，值得信赖。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 70}`\n\ninput：是出生就有，是血管瘤，在眼晴和鼻子傍边，小时侯烤电，现在剩下很少。你们是在那里。\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：真的假的\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 60}`\n\ninput：可以\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 50}`\n\ninput：@૮₍ ˶•-•˶₎ა(O639511218)\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 40}`\n\ninput：能不能出个纹身的过程视频看看\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 30}`\n\ninput:50度的烧酒多少钱一瓶\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput: [玫瑰][玫瑰][玫瑰][赞][赞][赞]\nreply: `{\"intent_to_purchase\": false}``{\"intent_score\": 0}`\n\ninput：123456\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n\ninput：15911137891\nreply: `{\"intent_to_purchase\": true }``{\"intent_score\": 90}`\n \ninput：有屁用还吹，赚你\n妈，坑比，全是骗人的\nreply: `{\"intent_to_purchase\": false }``{\"intent_score\": 0}`\n注意<只有表情符>无法判断意图。\n注意<提供了联系方式>表示具有意图。\n注意<用户询问店铺或者公司等线下地址>属于具有意图。\n注意<与服务无关内容>无法判断意图。\n注意<咨询是否真实有效>属于有意图。\n注意请在最后给出你的原因。\n\n<user input>\n {car}\n \n<your reply>\n"
            #房屋类型+交房终版
            # request.query="[历史对话信息]'''"+query['input']+prompt_hometype_jiaofangv6_xinjiu
            # request.query=prompt.format(car=query['input'])
            print(query['first_industry_name'])
            if query['first_industry_name']=='交通' or query['first_industry_name']=='汽车':
                prompt=prompt_carv2
            elif query['first_industry_name']=='家居建材':
                prompt=prompt_decov2
            elif query['first_industry_name']=='生活服务':
                prompt=prompt_livev2
            

            request.query=prompt_format.format(question=prompt.replace("{car}",str(query['input'])))
            #房屋信息提取
            # request.query="[历史对话信息]'''"+query['input']+prompt_homeinfo_v3_2
            request.config['output_len']="-1"
            print(request.query)
            #发起请求
            resp = grpc_client.Chat(request, timeout=time_out)
            resp = json.loads(MessageToJson(resp))
            if resp['status']['code'] != 'SUCESS':
                logger.info('%s 接口调用失败,重试 %d, status_code=%s', query[id_key], i+1, resp['status']['code'])
                time.sleep(random.randint(i*10, (i+1)*10))
                time_out += time_out
                continue
            else:
                return (0, resp)   
        except Exception as e:
            logger.error('%s 发生异常,重试 %d: %s', query[id_key], i+1, e)
            time.sleep(random.randint(i*10, (i+1)*10))
            time_out += time_out
            continue  
    logger.info("request:%s",request)
    logger.info('%s 重试 %d 次后仍失败', request.req_id, n_times)
    return (1, resp) 


def chat(grpc_client: GrpcClient, timeout: float, in_fn, out_fn, gpt_version, id_key='id'):
    #构造request, biz需根据实际申请的进行修改
    assert gpt_version in ['gpt3', 'gpt3.5', 'gpt4', 'kuaiyi']
    #biz = 'liupengli_699d56a9_gpt4'
    #biz = 'liupengli_699d56a9_gpt3.5'
    #biz='api_test'
    biz='luoyunkun_dee719d0_base_66b'
    #biz='api_66b_test'
    #biz = 'zhaoyi07_60c690ac_gpt4'
    if gpt_version == 'gpt4':
        biz = 'zhaoyi07_60c690ac_gpt4'
    
    request = MmuChatGptRequest(biz=biz)

    done_cases = {}
    if os.path.isfile(out_fn):
        with open(out_fn, 'r') as f:
            for line in f:
                x = json.loads(line.strip())
                done_cases[x[id_key]] = 1

    with open(in_fn, 'r') as fin, open(out_fn, 'a') as fo:
        for line in fin:
            x = json.loads(line.strip())
            if x[id_key] in done_cases:
                continue
            status, resp = process_with_retry(grpc_client, request, x, timeout, 1, id_key)  
            print(resp)
            if status != 0:
                continue
            if resp['status']['code'] != 'SUCESS':
                logger.error('%s 接口调用失败, status_code=%s', x[id_key], resp['status']['code'])
                continue
            try:
                x['prompt_input']=request.query
                x['answer'] = resp['answer']
                json_str = json.dumps(x, ensure_ascii=False)
                fo.write(json_str + '\n')
                fo.flush()                
                logger.info(x[id_key] + '\tdone')
            except Exception as e:
                logger.error('发生异常 %s\t%s', x[id_key], e)
                # print(resp)
                continue

if __name__ == "__main__":
    #服务名不要改动
    client_option = ClientOption(
        biz_def='mmu',
        grpc_service_name='mmu-chat-gpt-service',
        grpc_stub_class=MmuChatGptServiceStub
    )

    client = GrpcClient(client_option)
    chat(client, 160, sys.argv[1], sys.argv[2], sys.argv[3], id_key='id') #输入文件的id字段在这儿配置
    logger.info('call end')



